blog_on_rails/config/routes.rb
Rails.application.routes.draw do
  get('/',{to: 'welcome#index', as: :root})
  resources :posts do
    resources :comments, only: [:create,:destroy], shallow: true
  end
  resources :users, only: [:new, :create, :edit, :update]
  resource :session, only: [:new, :create, :destroy]
  patch('/users/:id/password', {to: 'users#update_password', as: :update_password})
end


# PATCH/PUT	/photos/:id	photos#update	update a specific photo

blog_on_rails/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.is_admin?
        can :manage, :all
      else
        can :read, :all
      end
    # #


    can :manage, Post do |post|
      post.user == user
    end
    can :manage, Comment do |comment|
      comment.user == user || comment.post.user == user
    end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

blog_on_rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blog_on_rails/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

blog_on_rails/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :nullify
  validates :body, presence: true
  validates_length_of :body, minimum: 50, message: "Your blog post must be at least 50 characters long."
  validates :title, presence: true, uniqueness: true
end

blog_on_rails/app/models/user.rb
class User < ApplicationRecord
has_many :comments, dependent: :nullify
has_many :posts, dependent: :nullify

has_secure_password
validates :first_name, :last_name, presence: true

VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

validates :email,
presence: true,
uniqueness: true,
format: VALID_EMAIL_REGEX

end

blog_on_rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def user_signed_in?
    current_user.present?
  end
  helper_method :user_signed_in?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id].present?
  end
  helper_method :current_user

  def authenticate_user!
    unless user_signed_in?
      flash[:alert] = 'You must sign up or sign in first'
      redirect_to new_session_path
    end
  end
end

blog_on_rails/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :authenticate_user!
before_action :find_comment, :authorize_user!, only: [:destroy]

  def destroy
    @comment.destroy
    redirect_to post_path(@comment.post)
  end

  def create
    @post = Post.find params[:post_id]
    puts "@post: #{@post}"
    @comment = Comment.new comment_params
    @comment.post = @post
    @comment.user = current_user

    if @comment.save
      redirect_to post_path(@post)
    else
      @comments = @post.comments.order(created_at: :desc)
      render 'posts/show'
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end

  def find_comment
    @comment = Comment.find params[:id]
  end


      def authorize_user!
        unless can?(:manage, @comment)
          flash[:alert] = 'Access Denied!'
          redirect_to root_path
        end
      end

end

# def create
#     @post = Question.find params[:post_id]
#     @answer = Answer.new answer_params
#     @answer.post = @post
#     @answer.user = current_user
#
#     if @answer.save
#       redirect_to post_path(@post)
#     else
#       @answers = @post.answers.order(created_at: :desc)
#       render 'posts/show'
#     end
#   end

blog_on_rails/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:edit,:show,:update,:destroy]
  before_action :authorize_user!, only: [:edit,:update,:destroy,]
  before_action :authenticate_user!, only: [:new,:edit,:update,:destroy,:create]
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def show


    @comments = @post.comments
    @comment = Comment.new
    # render json: @question
  end

  def update

    if @post.update post_params
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end


  def create
      @post = Post.new post_params
      @post.user = current_user

      if @post.save
        redirect_to post_path(@post)
      else
        render :new
        # @post.errors.full_message
      end
    end

private
    def post_params
      #require will extract a nested hash from the params by its keys name
      params.require(:post).permit(:title, :body)
    end

    def find_post
      @post = Post.find params[:id]
    end

    def authorize_user!
      unless can?(:manage, @post)
        flash[:alert] = 'Access Denied!'
        redirect_to new_session_path
      end
    end

end

blog_on_rails/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    end

    def create
      user = User.find_by(email: session_params[:email])

      if user&.authenticate(session_params[:password])
        session[:user_id] = user.id
        flash[:notice] = 'Thank you for signing in!'
        redirect_to root_path
      else
        flash.now[:alert] = 'Wrong email or password!'
        render :new
      end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = 'Signed out!'
        redirect_to root_path
    end

  private
  def session_params
    params.require(:session).permit(:email, :password)
  end

  end

blog_on_rails/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
     @user = User.new
  end

  def edit
    @user = User.find params[:id]
  end


  def update
    @user = User.find params[:id]
    if @user.update user_params
      redirect_to root_path
    else
      render :edit
    end
  end

  def update_password
    @user = User.find params[:id]
    if @user.authenticate(params[:user][:old_password]) == @user
      if params[:user][:old_password] == params[:user][:password]
        flash[:notice] = 'Old password is equal to new password!'
        render :edit
      elsif @user.update password_params
        redirect_to root_path
      else
        render :edit
      end
    else
      flash[:notice] = 'Old password is incorrect!'
      render :edit
    end
  end

  def create
      @user = User.new user_params

      if @user.save
        session[:user_id] = @user.id
        flash[:notice] = "Thank you for signing up!"
        redirect_to root_path
      else
        render :new
      end
    end

  private
  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :email,
      :password,
      :password_confirmation
    )
  end

  def password_params
    params.require(:user).permit(
      :password,
      :password_confirmation
    )
  end


end

blog_on_rails/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
def index
  redirect_to posts_path
end
end

blog_on_rails/app/helpers/application_helper.rb
module ApplicationHelper
end

blog_on_rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogOnRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-expand navbar-primary bg-light">
    <a class="navbar-brand" href="<%= posts_path %>">Blog on Rails</a>
    <div class="collapse navbar-collapse flex-row-reverse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="<%= posts_path %>">Home<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= new_post_path %>">New Post</a>
        </li>
        <% if user_signed_in? %>
        <li class="nav-item">
          <a class="nav-link" href="<%= edit_user_path(current_user) %>"> Hello, <%= current_user.first_name %></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= session_path %>" data-method="delete"> Sign Out</a>
        </li>
                <% else %>
                <li class="nav-item">
                  <a class="nav-link" href="<%= new_session_path %>"> Sign In</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="<%= new_user_path %>"> Sign Up</a>
                </li>
            <% end %>
      </ul>
    </div>
  </nav>

<% if flash[:notice].present? %>

<div class="alert alert-primary" role="alert">
  <%= flash[:notice] %>
</div>

<% end %>
<% if flash[:alert].present? %>

<div class="alert alert-primary" role="alert">
  <%= flash[:alert] %>
</div>

<% end %>




</div>
  <div class="container-fluid">
        <%= yield %>
      </div>
  </body>
</html>

blog_on_rails/app/views/posts/_form.html.erb
<%= form_for @post do |f|%>

<% if @post.errors.present? %>
  <p><%= @post.errors.full_messages.join(', ') %></p>
  <% end %>
<div class="">
  <%= f.label :title %>
  <%= f.text_field :title, class: "form-control" %>
</div>

<div class="">
  <%= f.label :body %>
  <%= f.text_area :body, class: "form-control" %>
</div>
<br>
<div class="">
  <%= f.submit %>
</div>


<% end %>

blog_on_rails/app/views/posts/edit.html.erb
<%= render 'form' %>

blog_on_rails/app/views/posts/index.html.erb
<div class="posts-body">
<% @posts.each do |post| %>
  <div class="post-card align-self-stretch m-2 p-1">
    <div class="card-block">
      <a href="<%= post_path(post) %>"><h4 class="card-title text-primary"  ><%= post.title %></h4></a>
      <p class="card-text"><%= post.body.slice(0,50) + ' ...' %></p>
    </div>
  </div>
<% end %>

</div>

blog_on_rails/app/views/posts/new.html.erb
<%= render 'form' %>

blog_on_rails/app/views/posts/show.html.erb
<h2><%= @post.title %></h2>

<p><%= @post.body %></p>

<p><small>
  Posted <%= time_ago_in_words(@post.created_at)%> ago
  •
  Last edited <%= time_ago_in_words @post.updated_at %> ago

</small></p>



<% if can?(:manage, @post) %>
<div class="">
  <%= link_to 'Edit', edit_post_path(@post) %>
  |
  <%= link_to 'Delete',
  post_path(@post),
  method: :delete,
  data: {
    confirm: 'Are you sure?'
  }
  %>
</div>


<% end %>

<h3>Answers</h3>

<%= form_for [@post,@comment] do |f| %>
<% if @comment.errors.present? %>
  <%= @comment.errors.full_messages.join(', ') %>
<% end %>
<div class="">
  <%= f.text_area :body, placeholder: "What's on your mind?" %>
</div>
<%= f.submit "Answer Question" %>
<% end %>

<hr>
<div class="comment-list">
  <% @comments.each do |comment| %>
    <div class="comment-list-item">
      <p><%= comment.body %><br>
        <small>
        Posted <%= time_ago_in_words(comment.created_at)%> ago
      </small>
      <small>

<% if can?(:manage, comment)  %>
        •
        <%= link_to 'Delete',
         comment_path(comment),
         method: :delete,
         data: {
           confirm: 'Are you sure?'
         }
         %>
         <% end %>
      </small>
  </p>
      <hr>

    </div>
  <% end %>
</div>

blog_on_rails/app/views/users/_form.html.erb
<%= form_for @user do |f|%>

<% if @user.errors.present? %>
  <p><%= @user.errors.full_messages.join(', ') %></p>
  <% end %>
<div class="">
  <%= f.label :first_name %>
  <%= f.text_field :first_name, class: "form-control" %>
</div>
<div class="">
  <%= f.label :last_name %>
  <%= f.text_field :last_name, class: "form-control" %>
</div>

<div class="">
  <%= f.label :email %>
  <%= f.text_field :email, class: "form-control" %>
</div>
<div class="">
  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control" %>
</div>
<div class="">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: "form-control" %>
</div>
<br>
<div class="">
  <%= f.submit %>
</div>


<% end %>

blog_on_rails/app/views/users/edit.html.erb
<h2>Edit User Details</h2>

<%= form_for @user do |f|%>

<% if @user.errors.present? %>
  <p><%= @user.errors.full_messages.join(', ') %></p>
  <% end %>
<div class="">
  <%= f.label :first_name %>
  <%= f.text_field :first_name, class: "form-control" %>
</div>
<div class="">
  <%= f.label :last_name %>
  <%= f.text_field :last_name, class: "form-control" %>
</div>

<div class="">
  <%= f.label :email %>
  <%= f.text_field :email, class: "form-control" %>
</div>
<br>
<div class="">
  <%= f.submit %>
</div>

<% end %>
<br>

<h2>Change Password</h2>

<%= form_for @user, url:update_password_path do |f| %>

<% if @user.errors.present? %>
  <p><%= @user.errors.full_messages.join(', ') %></p>
  <% end %>
  <div class="">
    <%= f.label :old_password %>
    <%= f.password_field :old_password, class: "form-control" %>
  </div>
  <div class="">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  </div>

  <div class="">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>
  <br>
  <div class="">
    <%= f.submit %>
  </div>

  <% end %>

blog_on_rails/app/views/users/new.html.erb
<%= render 'form' %>

blog_on_rails/app/views/welcome/index.html.erb
<div class="posts-body">
<% @posts.each do |post| %>
  <div class="card m-3 p-3 col-4">
    <div class="card-block">
      <h4 class="card-title text-primary"><%= post.title %></h4>
      <p class="card-text"><%= post.body %></p>
    </div>
  </div>
<% end %>

</div>